export const itemsList = [
  {
    id: 1,
    title: "Lamp",
    img: "lamp1.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "20.90",
  },
  {
    id: 2,
    title: "Aroma Candle",
    img: "aroma-candle1.jpg",
    desc: "Candles create atmospheric light and are a beautiful decorative element.",
    category: "aroma",
    price: "5.50",
  },
  {
    id: 3,
    title: "Green Sofa",
    img: "sofa1.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "599.99",
  },
  {
    id: 4,
    title: "White Chair",
    img: "chair1.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "55.70",
  },
  {
    id: 5,
    title: "Craft Vase",
    img: "vase1.jpg",
    desc: "The vase is unique, because it is made of craft by master craftsmen.",
    category: "vases",
    price: "10.60",
  },
  {
    id: 6,
    title: "Wooden Table",
    img: "table1.jpg",
    desc: "Stylish table suitable for any interior.",
    category: "tables",
    price: "150.50",
  },
  {
    id: 7,
    title: "Wooden Chair",
    img: "chair2.jpg",
    desc: "A middle chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "70.98",
  },
  {
    id: 8,
    title: "Aroma Diffuser",
    img: "aroma-diffuser1.jpg",
    desc: "An elegant glass bottle filled with a special perfumed liquid.",
    category: "aroma",
    price: "15.70",
  },
  {
    id: 9,
    title: "Lamp",
    img: "lamp2.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "100.80",
  },
  {
    id: 10,
    title: "Wooden Wardrobe",
    img: "wardrobe1.jpg",
    desc: "A functional and spacious wardrobe will suit any interior.",
    category: "warderobes",
    price: "399.99",
  },
  {
    id: 11,
    title: "Chair",
    img: "chair3.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "60.89",
  },
  {
    id: 12,
    title: "Vase",
    img: "vase2.jpg",
    desc: "The vase is unique, because it is made of blown glass by master craftsmen.",
    category: "vases",
    price: "15.00",
  },
  {
    id: 13,
    title: "Table",
    img: "table3.jpg",
    desc: "Stylish table suitable for any interior.",
    category: "tables",
    price: "180.00",
  },
  {
    id: 14,
    title: "Sofa",
    img: "sofa2.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "500.00",
  },
  {
    id: 15,
    title: "Chair",
    img: "chair4.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "60.00",
  },
  {
    id: 16,
    title: "Lamp",
    img: "lamp3.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "80.00",
  },
  {
    id: 17,
    title: "Chair",
    img: "chair5.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "70.00",
  },
  {
    id: 18,
    title: "Aroma Diffuser",
    img: "aroma-diffuser2.jpg",
    desc: "An elegant glass bottle filled with a special perfumed liquid.",
    category: "aroma",
    price: "15.00",
  },
  {
    id: 19,
    title: "Vase",
    img: "vase3.jpg",
    desc: "The vase is unique, because it is made of clay by masters of their craft.",
    category: "vases",
    price: "20.00",
  },
  {
    id: 20,
    title: "Table",
    img: "table4.jpg",
    desc: "Stylish table suitable for any interior.",
    category: "tables",
    price: "200.00",
  },
  {
    id: 21,
    title: "Lamp",
    img: "lamp4.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "30.00",
  },
  {
    id: 22,
    title: "Archair",
    img: "chair6.jpg",
    desc: "A small and tidy armchair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "90.00",
  },
  {
    id: 23,
    title: "Vase",
    img: "vase4.jpg",
    desc: "The vase is unique, because it is made of blown glass by master craftsmen.",
    category: "vases",
    price: "15.00",
  },
  {
    id: 25,
    title: "Table",
    img: "table5.jpg",
    desc: "Stylish table suitable for any interior.",
    category: "tables",
    price: "180.00",
  },
  {
    id: 26,
    title: "Aroma Diffuser",
    img: "aroma-diffuser3.jpg",
    desc: "An elegant glass bottle filled with a special perfumed liquid.",
    category: "aroma",
    price: "15.00",
  },
  {
    id: 27,
    title: "Chair",
    img: "chair7.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "50.00",
  },
  {
    id: 28,
    title: "Lamp",
    img: "lamp5.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "100.00",
  },
  {
    id: 29,
    title: "Vase",
    img: "vase5.jpg",
    desc: "The vase is unique, because it is made of blown glass by master craftsmen.",
    category: "vases",
    price: "20.00",
  },
  {
    id: 30,
    title: "Sofa",
    img: "sofa3.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "550.00",
  },
  {
    id: 31,
    title: "Table",
    img: "table6.jpg",
    desc: "Stylish table suitable for any interior.",
    category: "tables",
    price: "250.00",
  },
  {
    id: 32,
    title: "Chair",
    img: "chair8.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "70.00",
  },
  {
    id: 33,
    title: "Aroma Diffuser",
    img: "aroma-diffuser4.jpg",
    desc: "An elegant glass bottle filled with a special perfumed liquid.",
    category: "aroma",
    price: "15.00",
  },
  {
    id: 34,
    title: "Vase",
    img: "vase6.jpg",
    desc: "The vase is unique, because it is made of clay by masters of their craft.",
    category: "vases",
    price: "17.00",
  },
  {
    id: 35,
    title: "Armchair",
    img: "chair9.jpg",
    desc: "A small and tidy armchair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "90.00",
  },
  {
    id: 36,
    title: "Lamp",
    img: "lamp6.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "80.00",
  },
  {
    id: 37,
    title: "Vase",
    img: "vase7.jpg",
    desc: "The vase is unique, because it is made of blown glass by master craftsmen.",
    category: "vases",
    price: "15.00",
  },
  {
    id: 38,
    title: "Sofa",
    img: "sofa8.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "550.00",
  },
  {
    id: 39,
    title: "Aroma Candle",
    img: "aroma-candle2.jpg",
    desc: "Candles create atmospheric light and are a beautiful decorative element.",
    category: "aroma",
    price: "8.00",
  },
  {
    id: 40,
    title: "Vase",
    img: "vase8.jpg",
    desc: "The vase is unique, because it is made of clay by masters of their craft.",
    category: "vases",
    price: "17.00",
  },
  {
    id: 41,
    title: "Chair",
    img: "chair10.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "70.00",
  },
  {
    id: 42,
    title: "Lamp",
    img: "lamp7.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "100.00",
  },
  {
    id: 43,
    title: "Table",
    img: "table2.jpg",
    desc: "Stylish table suitable for any interior.",
    category: "sofas",
    price: "120.00",
  },
  {
    id: 44,
    title: "Aroma Diffuser",
    img: "aroma-diffuser5.jpg",
    desc: "An elegant glass bottle filled with a special perfumed liquid.",
    category: "aroma",
    price: "15.00",
  },
  {
    id: 45,
    title: "Sofa",
    img: "sofa4.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "550.00",
  },
  {
    id: 46,
    title: "Vase",
    img: "vase9.jpg",
    desc: "The vase is unique, because it is made of blown glass by master craftsmen.",
    category: "vases",
    price: "17.00",
  },
  {
    id: 47,
    title: "Armchair",
    img: "chair11.jpg",
    desc: "A small and tidy armchair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "90.00",
  },
  {
    id: 48,
    title: "Lamp",
    img: "lamp8.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "150.00",
  },
  {
    id: 49,
    title: "Sofa",
    img: "sofa5.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "500.00",
  },
  {
    id: 50,
    title: "Table",
    img: "table7.jpg",
    desc: "Stylish table suitable for any interior.",
    category: "tables",
    price: "300.00",
  },
  {
    id: 51,
    title: "Sofa",
    img: "sofa6.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "550.00",
  },
  {
    id: 52,
    title: "Chair",
    img: "chair12.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "80.00",
  },
  {
    id: 53,
    title: "Lamp",
    img: "lamp9.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "50.00",
  },
  {
    id: 54,
    title: "Sofa",
    img: "sofa7.jpg",
    desc: "Seat cushions filled with highly resilient polyurethane foam and polyester fiber wadding provide exceptional comfort.",
    category: "sofas",
    price: "600.00",
  },
  {
    id: 55,
    title: "Vase",
    img: "vase10.jpg",
    desc: "The vase is unique, because it is made of blown glass by master craftsmen.",
    category: "vases",
    price: "19.00",
  },
  {
    id: 56,
    title: "Aroma Candle",
    img: "aroma-candle3.jpg",
    desc: "Candles create atmospheric light and are a beautiful decorative element.",
    category: "aroma",
    price: "5.00",
  },
  {
    id: 57,
    title: "Chair",
    img: "chair13.jpg",
    desc: "A small and tidy chair that looks just as good in the living room as it does in the bedroom or hallway - even if space is tight.",
    category: "chairs",
    price: "50.00",
  },
  {
    id: 58,
    title: "Lamp",
    img: "lamp10.jpg",
    desc: "Stylish lamp that will suit any interior.",
    category: "lamps",
    price: "40.00",
  },
];
